### ISSUE TITLE
Typescript Typings

### ISSUE THREAD

**Issue by gavinharriscolab** [douglasjunior/react-native-get-location#10]
I am using React Native with Typescript. When importing the library Typescript complains about the lack of Typings for the module.

- How did you link to the library (autolinking, manual, rn link, cocoapods)? - Autolinking
- What version of React Native? - 0.63.0
- What version of the library? - 1.4.2
- iOS/Android version? - Android 30 (not building for iOS
- Did the problem happen after updating React Native? - Feature request, not an issue
- Are you using the library for the first time? - Yes
- It's a bug? Provide a link to a minimal reproduction case. - Not a bug.

**Comment by douglasjunior** [comment]
This library don't use TypeScript, so the complains are expected.

**Comment by gavinharriscolab** [comment]
I'm just putting together some TypeScript types (via in index.d.ts files, hope they are correct, seem to work out okay on my project) that can be shipped with the module, this will allow us TypeScript users to utilize this module without the implied `any` types.
I shall submit a PR for this once I am happy with it. 
Thanks for the module BTW!!

**Comment by douglasjunior** [comment]
Awesome! Thanks @gavinharriscolab !

**Comment by douglasjunior** [comment]
Closed by #11
