### ISSUE TITLE
Does not work on Simulator/Emulator 

### ISSUE THREAD

**Issue by ahmad-crossplatform** [douglasjunior/react-native-get-location#12]
Hello there , 
The library works fine on my ios Device , however it is not the case for  ios simulators and android emulator . 
I always get the position null .

**Comment by douglasjunior** [comment]
You need to configure the emulator to simulate the geographical position, in to the code there is no difference between the simulator and a physical device.

**Comment by douglasjunior** [comment]
iOS: https://willowtreeapps.com/ideas/simulating-location-in-ios

Android: https://willowtreeapps.com/ideas/simulating-location-in-ios
