### ISSUE TITLE
location returning null sometimes on ios and android both

### ISSUE THREAD

**Issue by bhuvin25** [douglasjunior/react-native-get-location#13]
- How did you link to the library (autolinking, manual, rn link, cocoapods)? - Yes
- What version of React Native? - 0.62.5
- What version of the library? - 1.4.3
- iOS/Android version? android api level - 28, ios - 10 onwards
- Did the problem happen after updating React Native? - problem from start
- Are you using the library for the first time? - yes
- It's a bug? Provide a link to a minimal reproduction case.

**Comment by douglasjunior** [comment]
Please, provide a minimal example which reproduce this problem.

**Comment by baatten** [comment]
I get null no matter what I do. just using the example code. error on both phone and sim:

GetLocation.getCurrentPosition({
            enableHighAccuracy: false,
            timeout: 15000,
        })
        .then(location => {
            console.log(location);
        })
        .catch(error => {
            const { code, message } = error;
            console.warn(code, message);
        })

**Comment by douglasjunior** [comment]
Sorry, but that is not enough for me to try to help.

We are using the library in several projects in production with no problem.

I need more information on how to simulate the problem, and if possible, provide a minimal example which reproduce this problem.

**Comment by baatten** [comment]
Thanks for answer, will try a different lib for now.

**Comment by DaScientist** [comment]
I got the same kind of error when using with TS. The parser says the package doesn't have any default export, but if we do:
`import * as GetLocation from 'react-native-get-location';`
then it throws the null. At the same time, if we do:
`import GetLocation from 'react-native-get-location';`
Then the parser says no.

I think it's a problem in the type declaration file

**Comment by douglasjunior** [comment]
Make sense @DaScientist, I have no experience with typescript, so any help is welcome.

**Comment by DaScientist** [comment]
Sure. Will surely love to send a pull request when I can.

**Comment by douglasjunior** [comment]
Guys, could you please try this branch with TypeScript?

```sh
 yarn add react-native-get-location@https://github.com/douglasjunior/react-native-get-location#types-definition
```
 
 and then
 
 ```js
 import GetLocation from 'react-native-get-location';
 ```

**Comment by yogesch** [comment]
> Thanks for answer, will try a different lib for now.

Which library did you finally go with? I have the exact same problem with this one.
