### ISSUE TITLE
iOS and Android Timestamp Difference

### ISSUE THREAD

**Issue by WrathChaos** [douglasjunior/react-native-get-location#15]
Hello @douglasjunior,
Awesome library! Actually, it works better than [RN Geolocation](https://github.com/react-native-geolocation/react-native-geolocation). Thank you for the library.

I have a question, on the iOS side library's `time` property does not give me milliseconds by default but on the Android side, it gives me milliseconds by default. Is there a reason for that? 

- How did you link to the library (autolinking, manual, rn link, cocoapods)?
-> Autolinking, Cocoapods
- What version of React Native?
-> RN 0.63.5
- What version of the library?
-> 1.4.3
- iOS/Android version?
-> iOS 14.2, Android 9
- Did the problem happen after updating React Native?
-> Yes
- Are you using the library for the first time?
-> No

**Comment by douglasjunior** [comment]
Hi @WrathChaos, thanks for the feedback! 😃 

About the `time`, iOS works with seconds, and Android with milliseconds, and you are right, today we don't convert to milliseconds before return the `time` value.

https://github.com/douglasjunior/react-native-get-location/blob/b03a7b21a9157d1de7f131c80ba46fa9c2626ef3/ios/ReactNativeGetLocationLibrary/LocationModule.m#L112

**Comment by WrathChaos** [comment]
I think you should write this on your README, this would be great time saver :)

**Comment by douglasjunior** [comment]
I think we can just convert to milliseconds and maintain universal usage between Android and iOS.

**Comment by WrathChaos** [comment]
As you wish, both would be work :) Please let me know when it is converted.

**Comment by douglasjunior** [comment]
We will keep this issue open until the correction, I should check it out soon.

**Comment by douglasjunior** [comment]
Fixed on `2.0.0`.
