### ISSUE TITLE
I only get TIMEOUT Location timed out using the GetLocation.getCurrentPosition function

### ISSUE THREAD

**Issue by potatosenior** [douglasjunior/react-native-get-location#17]
- How did you link to the library (autolinking, manual, rn link, cocoapods)? autolinking
- What version of React Native? 0.64.4
- What version of the library? 2.0.0
- iOS/Android version? Android 29.0
- Did the problem happen after updating React Native? no
- Are you using the library for the first time? yes
- It's a bug? Provide a link to a minimal reproduction case. i dont think so

![image](https://user-images.githubusercontent.com/55155875/103964799-14ded400-513b-11eb-95ae-4dedb886c970.png)

**Comment by potatosenior** [comment]
White the default config of the tutorial.

**Comment by douglasjunior** [comment]
Timeout means that your device was unable to obtain the location within the specified time.

If necessary, increase the timeout time for your device.

**Comment by potatosenior** [comment]
i tried even with 60 seconds :(

**Comment by douglasjunior** [comment]
The time to obtain the location depends on a number of factors, quality of your device's GPS sensor, weather condition, building where you are, etc.

If the location could not be obtained in 60 seconds, then probably no location was found.
