### ISSUE TITLE
can't get user location in Android

### ISSUE THREAD

**Issue by preflower** [douglasjunior/react-native-get-location#20]
- How did you link to the library (autolinking, manual, rn link, cocoapods)?
- autolinking
- What version of React Native?
- 0.64.0
- What version of the library?
- ^2.1.0
- iOS/Android version?
- 10
- Did the problem happen after updating React Native?
- no
- Are you using the library for the first time?
- yes
- It's a bug? Provide a link to a minimal reproduction case.
- yes, because when in use `@react-native-community/geolocation` library, i can get user location in Android; but library has error about timeout, so i decide to use `react-native-get-location` to alternative it

**Comment by douglasjunior** [comment]
Thanks for the feedback, but you haven't provided any relevant information for me to help you. 

What I can say is that the problem that causes you to get "timeout" with `@react-native-community/geolocation` is probably the same problem that makes `react-native-get-location` to not work.

**Comment by preflower** [comment]
`@react-native-community/geolocation` timeout error is https://github.com/react-native-geolocation/react-native-geolocation/issues/139, and i can get location if i allow; but when i alternative to `react-native-get-location`, i can't get user location even if allow permission; :(

**Comment by preflower** [comment]
what info do i need to provide?

**Comment by douglasjunior** [comment]
- The error with https://github.com/react-native-geolocation/react-native-geolocation/issues/139 is on iOS, your problem with `react-native-get-location` is on iOS too?
- Simulator or real device?
- You checked de device permissions?
- Have any error messages?
- Snippet code that you are using to get location?

**Comment by preflower** [comment]
```
async function moveToLocation (): Promise<void> {
    GetLocation.getCurrentPosition({
      enableHighAccuracy: true,
      timeout: 15000
    })
      .then(location => {
        console.log(location)
      })
      .catch(error => {
        const { code, message } = error
        console.warn(code, message)
      })
  }
```

**Comment by preflower** [comment]
i only get `TIMEOUT Location timed out` error;

**Comment by preflower** [comment]
i don't think is internal error about gps; because I can get location when I use @react-native-community/geolocation;

**Comment by preflower** [comment]
i find the error is what: https://stackoverflow.com/a/42995451;
and when i use GPS_PROVIDER `onLocationChanged` can't be trigger, but i manally set NETWORK_PROVIDER is work; so maybe we will need to use both GPS_PROVIDER  and NETWORK_PROVIDER;

**Comment by preflower** [comment]
![image](https://user-images.githubusercontent.com/30513719/117748555-cc4b3a80-b242-11eb-8a6c-1234ae70d30a.png)
I only modified this line and it worked; 
and maybe we can request `getLastKnownLocation` first (just enhance)

**Comment by preflower** [comment]
u'r right at the code level;
but i wanna get GPS_PROVIDER's location at first, and then use the NETWORK_PROVIDER if I cannot get it;
i'm so sad that library cannot satisfied my feature, maybe i need to use `@react-native-community/geolocation` library.
thx u response
