### ISSUE TITLE
Cannot read property 'getCurrentPosition' of undefined

### ISSUE THREAD

**Issue by ApWin** [douglasjunior/react-native-get-location#21]
- Autolinking 
- react-native:0.63.3
- Lib version: 2.1.0
- I just tested Android 11v
- Did the problem happen after updating React Native: No
- Are you using the library for the first time: Yeap

**Comment by douglasjunior** [comment]
Please, follow the installation steps. https://github.com/douglasjunior/react-native-get-location#install

With React Native 0.60+ you need to re-run the app to build the native code.
