### ISSUE TITLE
How to catch Speed

### ISSUE THREAD

**Issue by lucbraga** [douglasjunior/react-native-get-location#24]
Olá, existe alguma forma de capturar a velocidade no momento que eu pego a posição, ou apenas é possível calcular a velocidade comparando com a ultima posicão solicitada?

Hi, is there any way to capture the velocity at the moment I get the position, or is it only possible to calculate the velocity by comparing it to the last requested position?

Thank you.

**Comment by douglasjunior** [comment]
Its possible, the `speed` is returned inside the `location` object.

https://github.com/douglasjunior/react-native-get-location#object-location
