### ISSUE TITLE
Build Errors: Linking / Undefined Symbols

### ISSUE THREAD

**Issue by awaldron** [douglasjunior/react-native-get-location#25]
- How did you link to the library (autolinking, manual, rn link, cocoapods)?
autolinking

- What version of React Native?
0.66.3

- What version of the library?
2.1.2

- iOS/Android version?
iOS 15

- Did the problem happen after updating React Native?
No, fresh install of RN

- Are you using the library for the first time?
No, it was working previously in another app I'm building.

- It's a bug? Provide a link to a minimal reproduction case.
Probably?

I'm working on an app for a client and had to update some libraries for iOS 15 / Xcode 13. I now keep getting linking errors in that app for ReactNativeGetLocation. Just to be sure, I created a fresh RN app and installed only this library and I'm getting the same errors:

Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_RCTConvert", referenced from:
      objc-class-ref in LocationModule.o
  "_RCTRegisterModule", referenced from:
      +[LocationModule load] in LocationModule.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

![image](https://user-images.githubusercontent.com/310667/142918382-1a8d3d7f-afb3-4c5a-874f-c234db52ccf5.png)

**Comment by douglasjunior** [comment]
Thank you for the feedback!

I will try in a RN 66 app with Xcode 13 asap.

**Comment by douglasjunior** [comment]
@awaldron please try with 2.2.1 version.

I updated the Sample project to React Native 0.66.3 and tested it with Xcode 13.1 and iOS 15, it worked without any problem.

Then I took the opportunity to update the Android and iOS native projects inside the library, but apparently there were no changes.
