### ISSUE TITLE
its taking minimum 20 sec to get location of user. if i put 2 sec then it close the app. how can i fix this problem please help me

### ISSUE THREAD

**Issue by mohd-sher-khan** [douglasjunior/react-native-get-location#26]
- How did you link to the library (autolinking, manual, rn link, cocoapods)?
- What version of React Native?
- What version of the library?
- iOS/Android version?
- Did the problem happen after updating React Native?
- Are you using the library for the first time?
- It's a bug? Provide a link to a minimal reproduction case.

**Comment by douglasjunior** [comment]
Timeout is working as expected. Timeout sets a time limit that you want to wait until you receive the location, or give up. #17

If the app is closing then there are errors in your code, check the console logs if there is anything.
