### ISSUE TITLE
Location cancelled by user or by another request

### ISSUE THREAD

**Issue by alexchudnovsky** [douglasjunior/react-native-get-location#27]
Hi,

I am just wondering what does this message mean ?

Location cancelled by user or by another request

Thanks

**Comment by alexchudnovsky** [comment]
Specifically i am getting 

Location cancelled by another request

But can't work out what could be causing that

**Comment by douglasjunior** [comment]
Hi @alexchudnovsky, the "cancelled by user" will not occur, as it depends on the implementation of https://developers.google.com/android/reference/com/google/android/gms/tasks/CancellationToken

The "cancelled by another request" will occur if you run `getCurrentPosition` before the previous call completes.

**Comment by alexchudnovsky** [comment]
Thanks very much for your answer

**Comment by patrickrnelson** [comment]
@douglasjunior can you clarify which request gets cancelled? If you run `getCurrentPosition` before the previous call completes, does the initial call get cancelled? Or will the newest call get cancelled?

**Comment by douglasjunior** [comment]
> [@douglasjunior](https://github.com/douglasjunior) can you clarify which request gets cancelled? If you run `getCurrentPosition` before the previous call completes, does the initial call get cancelled? Or will the newest call get cancelled?

If the second request happens BEFORE the first one is completed, then the FIRST will be canceled.

Unfortunately, the Location API from Android and iOS doesn't support concurrent single requests.

**Comment by usman965** [comment]
In my case, the issue was due to a location emulator app on your Android testing device—there was nothing wrong with the code. You just opened the emulator app, started listening for position updates, and it worked.
