### ISSUE TITLE
GetLocation has no function to "Stop Getting Location"

### ISSUE THREAD

**Issue by natealmeida185** [douglasjunior/react-native-get-location#28]
Hello, I would like to ask if the developers could possibly add the functionality to cancel or stop GetLocation from getting the location. Whenever the user navigates in my application it crashes due to this issue of rerendering.

**Comment by douglasjunior** [comment]
Today, the request is cancelled only if you call another request in sequence.

About your problem, you should verify if your component is unmounted before to continue.

Example:

```js
useEffect(() => {
     let unmounted = false;

     const requestLocation = async () => {
           try {
                 const location = GetLocation.getCurrentPosition(props);
                 if (unmounted) return;
                 // continue
           } catch (err) {
                 // ...
           }
     };
     
     requestLocation();

     return () => {
         unmounted = true;
     };
}, []);
```

**Comment by BraveEvidence** [comment]
This will help https://www.youtube.com/watch?v=E7X9DjezSR0
