### ISSUE TITLE
How would this work if user is offline? i.e. lost connection for 1-2 mins

### ISSUE THREAD

**Issue by mominnawaf** [douglasjunior/react-native-get-location#29]
I need to build functionality where users can track location in offline mode too.
- How did you link to the library (autolinking, manual, rn link, cocoapods)?
- What version of React Native?
- What version of the library?
- iOS/Android version?
- Did the problem happen after updating React Native?
- Are you using the library for the first time?
- It's a bug? Provide a link to a minimal reproduction case.

**Comment by douglasjunior** [comment]
This library don't require that the users to be online.
