### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by gucomecan** [douglasjunior/react-native-get-location#30]
I noticed that this package includes more than what it said. Can you extend the doc. Right now these methods are not described:
openGpsSettings
openCelularSettings
openAppSettings
openWifiSettings

Or may be there is a reason for that?

**Comment by douglasjunior** [comment]
These methods are not documented because I can't guarantee that they will work, especially on iOS. 🥲

What I've been using is [Linking.openSettings()](https://reactnative.dev/docs/linking#opensettings).

**Comment by gucomecan** [comment]
Thanks for fast response.  But `openSettings()` from `Linking` open myApp setting, but instead I need device setting. I didn't test `openGpsSettings` on iOS and can't confirm that it works there, but at least it works on Android. So IMO it is good to be mentioned in your doc as Android only feature or something like that. Anyway good package. Thanks!
