### ISSUE TITLE
xcode warning purple

### ISSUE THREAD

**Issue by dkjeune** [douglasjunior/react-native-get-location#31]
Hi,
With Xcode 14, i have a warning purple for this function :
  **if (![CLLocationManager locationServicesEnabled]) {**

You can find this function on LocationModule.m line 43.

Can this warning cause application to crash ? Or is it ok ?

Thanks for help

**Comment by dkjeune** [comment]
it seems locationServicesEnabled is Deprecated.
https://developer.apple.com/documentation/corelocation/cllocationmanager/1620566-locationservicesenabled

**Comment by douglasjunior** [comment]
Fixed in version 3.0.0
