### ISSUE TITLE
Support 2nd argument [rationale] on Android

### ISSUE THREAD

**Issue by harunalrashyid** [douglasjunior/react-native-get-location#33]
Hello, based on recent changes google play policy that _Your app must display a prominent disclosure_. 
Did you have a plans to support the 2nd argument `rationale` when request permission on android platform?

Example:
```
PermissionsAndroid.request(permission, [rationale]);
```

source: [location-permission-policy](https://support.google.com/googleplay/android-developer/answer/9888170#location-permissions), [permission-android-request](https://reactnative.dev/docs/0.64/permissionsandroid#request)

**Comment by douglasjunior** [comment]
Added in version 3.0.0

**Comment by lucasalerv** [comment]
When calling the getCurrentPosition function and passing the rationale parameter in an object, I get the error "Can't find variable: rationale". I correct it by replacing "rationale" with "options.rationale" in line 77 of index.js
