### ISSUE TITLE
Getting Wrong coordinates

### ISSUE THREAD

**Issue by SurajMohanty02** [douglasjunior/react-native-get-location#37]
I got one coordinate which is 180km far away from previous coordinate and the interesting thing is the time gap between two coordinate is 30 sec. Please give help me .

**Comment by SurajMohanty02** [comment]
Sometimes also getting duplicate coordinates even i moved to another place

**Comment by douglasjunior** [comment]
The accuracy of the location that the library returns depends on many variables, like your device, weather condition, etc.

The library just calls the native location API from Android and iOS and returns it to React Native.
