### ISSUE TITLE
Not giving the accurate data 

### ISSUE THREAD

**Issue by Sagar6228** [douglasjunior/react-native-get-location#38]
Not giving the Accurate Data and some time works sometime doesn't

RN: 0.64.4

**Comment by SurajMohanty02** [comment]
same for me also

**Comment by douglasjunior** [comment]
Welcome to the GPS/location world guys. 😅

As I have said on other issues (#37, #26, #17), to get successful location it depends on many variables, like your device, weather condition, the roof of the building you are in, etc.

The library just calls the native location API from Android and iOS and returns it to React Native.

The only thing you can do is increase the timeout and create a way for the user to try again.
