### ISSUE TITLE
 [LocationError: Location not available] Location not available

### ISSUE THREAD

**Issue by dhanendral** [douglasjunior/react-native-get-location#40]
- How did you link to the library (autolinking, manual, rn link, cocoapods)?
-  autolinking
- What version of React Native?
- 0.70.6
- What version of the library?
- 3.0.1
- iOS/Android version?
- Android 12
- Did the problem happen after updating React Native?
- NO
- Are you using the library for the first time?
- Yes
- It's a bug? Provide a link to a minimal reproduction case.
- Just install through NPM and try below code 
- GetLocation.getCurrentPosition({
      enableHighAccuracy: true,
      timeout: 30000,
      rationale: {
        title: 'Location permission',
        message: 'The app needs the permission to request your location.',
        buttonPositive: 'Ok',
      },
    })
      .then(newLocation => {
        setLoading(false);
        setLocation(newLocation);
      })

**Comment by robertsonasc** [comment]
Try to clean data of your App in Android Settings, it will make you have to concede permission with the PermissionsAndroid again, and will refresh your dev ambient. That worked for me.

**Comment by douglasjunior** [comment]
This problem is related with the installation steps or with your device, not with the library itself.
