### ISSUE TITLE
Possible Unhandled Promise Rejection (id: 5): LocationError: Location cancelled by another request Error: Location cancelled by another request

### ISSUE THREAD

**Issue by mobdev2020** [douglasjunior/react-native-get-location#41]
- How did you link to the library (autolinking, manual, rn link, cocoapods)?
- What version of React Native?
- What version of the library?
- iOS/Android version?
- Did the problem happen after updating React Native?
- Are you using the library for the first time?
- It's a bug? Provide a link to a minimal reproduction case.

**Comment by douglasjunior** [comment]
https://github.com/douglasjunior/react-native-get-location#error-codes
