### ISSUE TITLE
Possible Unhandled Promise Rejection (id: 5): LocationError: Location cancelled by another request Error: Location cancelled by another request

### ISSUE THREAD

**Issue by mobdev2020** [douglasjunior/react-native-get-location#42]
React native latest version 71.0.1 

REACT-NATIVE-GET-LOCATION : 4.0.0

Please give me suggestion for fix the issue when app is background and kill mode got location error .

this issue only android 12 and 13

**Comment by douglasjunior** [comment]
This error is dispatched when one request is still running and you call another request.

https://github.com/douglasjunior/react-native-get-location/blob/29a3516188dca6fac85318526b9da4e6ef994bb5/ios/ReactNativeGetLocationLibrary/LocationModule.m#L164

https://github.com/douglasjunior/react-native-get-location/blob/29a3516188dca6fac85318526b9da4e6ef994bb5/android/src/main/java/com/github/douglasjunior/reactNativeGetLocation/util/GetLocation.java#L139
