### ISSUE TITLE
getCurrentLocation is returning UNAUTHORIZED

### ISSUE THREAD

**Issue by akabeera** [douglasjunior/react-native-get-location#44]
- How did you link to the library (autolinking, manual, rn link, cocoapods)?
autolinking
- What version of React Native?
0.72.3
- What version of the library?
4.0.0
- iOS/Android version?
Android
- Did the problem happen after updating React Native?
Problem occurs the very first time trying out the library
- Are you using the library for the first time?
Yes
- It's a bug? Provide a link to a minimal reproduction case.
Not sure but here is my code:

```
    useEffect(() => {
        console.log('get location')

        GetLocation.getCurrentPosition({
            enableHighAccuracy: true,
            timeout: 60000,
            rationale: {
        title: 'Location permission',
        message: 'The app needs the permission to request your location.',
        buttonPositive: 'Ok',
      },
        }).then((location) => {
            console.log('location: ', location)
        }).catch((error) => {
            const {code, message} = error
            console.log('error getting location: ', code, message)
        })
    }, [])
```

I've tried testing on both the emulator and physical device and both returns the same error code.  I've confirmed in app permissions that the app is allowing Location so I'm not sure what's causing this issue

![image](https://github.com/douglasjunior/react-native-get-location/assets/52304070/f65cbd7e-f80e-4460-9083-e1b877c9a376)

**Comment by douglasjunior** [comment]
Have you updated your AndroidManifest.xml? Can you send me the XML content please?

**Comment by akabeera** [comment]
I didn't, the readme specified this step is for API < 23, and I'm using 33, so I assumed I didn't need to do this.

![image](https://github.com/douglasjunior/react-native-get-location/assets/52304070/bef05a21-8caf-4802-aebf-c0cece065ba5)

**Comment by akabeera** [comment]
I've added the changes to my AndroidManifest file and it's working now.  Thanks for the clarification.  Closing this thread now.
