### ISSUE TITLE
Allow tracking location in a foreground service

### ISSUE THREAD

**Issue by daamsie** [douglasjunior/react-native-get-location#45]
I'm trying to use this library in a [foreground service](https://www.npmjs.com/~supersami) to track a user's location. 

Permissions are granted by the user when starting location tracking. I use a separate library to deal with that. 

My rough code looks like this

```
ReactNativeForegroundService.add_task(
        async () => {
          await trackCurrentLocation();
        },
        {
          delay: 30000,
          onLoop: true,
          ... ,
        },
      );
```
The trackCurrentLocation() function uses this library to get the current location and record it. 

```
const location = await GetLocation.getCurrentPosition({
        enableHighAccuracy: true,
        timeout: 60000,
        rationale: {
          title: 'Location permission',
          message: 'We need your location to be able to track your route',
          buttonPositive: 'OK',
          buttonNegative: 'Cancel',
        },
});
... does stuff with the location
```

This works fine when the app is open and active. However, if I close the app, the foreground service continues (yay!), but the getCurrentPosition() call fails. 

I have dug into it and the error being caught is `[Error: Tried to use permissions API while not attached to an Activity.]`

I dug into the library's code and found that it was requesting permission every time it's getting the location.  I commented out the permission requesting (I already handle that, so no need) and everything runs perfectly.

```
async getCurrentPosition(options = DEFAULT_OPTIONS) {
        const opts = { ...DEFAULT_OPTIONS, ...options };
        // if (OS === 'android') {
        //     await (0, utils_1.requestAndroidPermission)(opts.enableHighAccuracy, opts.rationale);
        // }
        try {
            return ReactNativeGetLocation.getCurrentPosition(opts);
        }
        catch (error) {
            if ((0, LocationError_1.isLocationError)(error)) {
                throw new LocationError_1.default(error.code, error.message);
            }
            throw error;
        }
    },
```

It seems like it will be impossible to use this reliably in a foreground service if the permissions request is bundled into the getCurrentPosition() method. 

I'm not sure what the best solution to this problem is but thought I'd share my findings as it shows how the permissions request implementation breaks foreground services. 

It would be great to have a way to use this without bundling in the permissions request.

- How did you link to the library: autolinking
- What version of React Native: 0.72
- What version of the library? 4.0.0
- iOS/Android version? Android 13
- Did the problem happen after updating React Native? No
- Are you using the library for the first time? Yes

**Comment by douglasjunior** [comment]
Good catch.

Primarily, this library was not made with the "location track" in mind. The main objective here is to replace the React Native geolocation API.

I think we can add a option to avoid request permission automatically, on Android this will be made as you suggest, but for iOS the permission is handled by the native code:

https://github.com/douglasjunior/react-native-get-location/blob/87a44afb8ef26f4ba7634b49b990d1b62e6a6aaf/ios/ReactNativeGetLocationLibrary/LocationModule.m#L170-L174

**Comment by daamsie** [comment]
Thanks for considering the extra option and for making this library available. I have tried various location tracking libraries and found this is actually the most reliable on Android when combined with a foreground task. Combined with a bit of my own logic to detect when a user is stopped, it does a great job with minimal battery consumption. I really like the simplicity of this library. 

From that snippet, it doesn't seem like iOS would have to request authorisation providing the user is already authorised. If the Android one behaved the same way it would probably be fine too. 

The problem in Android is that it _requests_ authorisation whether the user is authorised or not. Perhaps you could make use of the `PermissionsAndroid.check()` method and only request permissions if they weren't granted. Obviously it would fail if the user hasn't given permission, but that is to be expected. I think checking permissions will probably be fine in foreground task, though I have not tested that. If you like, I could try this approach and prepare a PR for you if it works well.

**Comment by douglasjunior** [comment]
Please, try with version `4.0.1`

**Comment by douglasjunior** [comment]
Consing, if you find any problem please let me know.
