### ISSUE TITLE
Xcode Warning "This method can cause UI unresponsiveness if invoked on the main thread. Instead, consider waiting for the `-locationManagerDidChangeAuthorization:` callback and checking `authorizationStatus` first."

### ISSUE THREAD

**Issue by StepanSavin** [douglasjunior/react-native-get-location#48]
I use automatic linking for this library.
React Native version - 0.72.1.
Library version - 4.0.1.
IOS - 17.2.1.

After building release version for IOS Xcode show me following warning - "This method can cause UI unresponsiveness if invoked on the main thread. Instead, consider waiting for the `-locationManagerDidChangeAuthorization:` callback and checking `authorizationStatus` first." in LocationModule.mm

I suppose that it can be the reason of unconsistent freezes in my RN app, but i am not sure. Maybe i just need to ignore it.

<img width="905" alt="image" src="https://github.com/douglasjunior/react-native-get-location/assets/88281291/86ec16e9-1bf1-4753-8206-7880a2388ef7">

**Comment by douglasjunior** [comment]
This method calls it's already inside the `locationManagerDidChangeAuthorization`, so this is not in the MAIN thread.

Take a look at this point:

https://github.com/douglasjunior/react-native-get-location/blob/3b4d22f4e03baaa7a9796d0ff7bdb24e642aadd7/ios/ReactNativeGetLocationLibrary/LocationModule.m#L43C1-L53C14

This change was made in version 3.0.0: https://github.com/douglasjunior/react-native-get-location/compare/2.2.1...3.0.0
