### ISSUE TITLE
get-location Permission Error

### ISSUE THREAD

**Issue by karakusnavy** [douglasjunior/react-native-get-location#5]
Hello, I get the following error when extracting my application apk.

![asdasd](https://user-images.githubusercontent.com/29973831/68146569-57aa8800-ff49-11e9-84ba-266e949eedef.png)

even though I allow it. Look at this:

![123](https://user-images.githubusercontent.com/29973831/68146669-93455200-ff49-11e9-8909-0e9f0833838c.png)

Help me please.

**Comment by douglasjunior** [comment]
Are your project using AndroidX?

**Comment by karakusnavy** [comment]
Yes. Look
![baba](https://user-images.githubusercontent.com/29973831/68148639-70b53800-ff4d-11e9-8900-7854cebff78a.png)

**Comment by douglasjunior** [comment]
You need to use [Jetifier](https://github.com/mikehardy/jetifier).

**Comment by karakusnavy** [comment]
I used but not working. Now give this error:

![notworking](https://user-images.githubusercontent.com/29973831/68151621-1d45e880-ff53-11e9-9d21-f4e5f73f23b3.png)


I try:

linking
reinstall
--save
npx jetifier

**Comment by douglasjunior** [comment]
Provide more information about your project, like React Native Version, using auto-linking or not, etc.

**Comment by karakusnavy** [comment]
![image](https://user-images.githubusercontent.com/29973831/68151837-84fc3380-ff53-11e9-98c9-678a5d1ef68b.png)

I use auto linking.

**Comment by douglasjunior** [comment]
So, you dont need to run the `react-native link`. However, this library is not ready to work with Cocoapods yet. 

So, it will work with auto-linking on Android, and not on iOS.

**Comment by karakusnavy** [comment]
Can you connect to the computer and examine in detail?

**Comment by karakusnavy** [comment]
I don't use IOS. I use Android. Can you help me ? How can i do this error?

**Comment by douglasjunior** [comment]
You need to learn about autolinking https://github.com/react-native-community/cli/blob/master/docs/autolinking.md

**Comment by karakusnavy** [comment]
Sir, I don't understand. How can i fix this error ? Help me please

**Comment by douglasjunior** [comment]
The version `1.3.0` should now work with RN 0.60.+ and autolinking, please update it.
