### ISSUE TITLE
Clarity on "UNAVAILABLE" error

### ISSUE THREAD

**Issue by patrickrnelson** [douglasjunior/react-native-get-location#50]
I'm just looking for a better understanding of when the "UNAVAILABLE" error can be triggered. What exactly is meant by "Location service is disabled", and how is that different from the "Authorization Denied" error.

For context, we have a user (app info below) who has been receiving the UNAVAILABLE error consistently over two weeks this past month and I am looking to understand what could be causing it.

- How did you link to the library (autolinking, manual, rn link, cocoapods)?
autolinking

- What version of React Native?
0.63.2

- What version of the library?
2.1.2

- iOS/Android version?
17.5.1

- Did the problem happen after updating React Native?
No

- Are you using the library for the first time?
No

- It's a bug? Provide a link to a minimal reproduction case.
No

**Comment by douglasjunior** [comment]
Hi @patrickrnelson, `UNAVAILABLE` error code means that the location service is disabled, don't exist on device or have some issues with the GPS hardware.

"Authorization Denied" is a description for the `UNAUTHORIZED` error code, that means the user reject the Location permission when requested by the app.
