### ISSUE TITLE
react-native-get-location:processDebugManifest

### ISSUE THREAD

**Issue by karthikkarunanithi91** [douglasjunior/react-native-get-location#51]
"react-native": "^0.73.8",

What went wrong:
Execution failed for task ':react-native-get-location:processDebugManifest'.
> A failure occurred while executing com.android.build.gradle.tasks.ProcessLibraryManifest$ProcessLibWorkAction
   > Incorrect package="com.github.douglasjunior.reactNativeGetLocation" found in source AndroidManifest.xml: C:\xxx\App\node_modules\react-native-get-location\android\src\main\AndroidManifest.xml.
     Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported.
     Recommendation: remove package="com.github.douglasjunior.reactNativeGetLocation" from the source AndroidManifest.xml: C:\xxx\App\node_modules\react-native-get-location\android\src\main\AndroidManifest.xml

**Comment by douglasjunior** [comment]
Good catch, thank you!

Fixed on version `5.0.0`.
