### ISSUE TITLE
 undefined Cannot read properties of undefined (reading 'getCurrentPosition')

### ISSUE THREAD

**Issue by rodrigodiasf1984** [douglasjunior/react-native-get-location#58]
- How did you link to the library (autolinking, manual, rn link, cocoapods)?
- yarn pod
- What version of React Native?
- 0.75.2
- What version of the library?
- ^5.0.0
- iOS/Android version?
- ios simulator
- Did the problem happen after updating React Native?
- no
- Are you using the library for the first time?
- yes
- It's a bug? Provide a link to a minimal reproduction case.

Hello, 

I'm doing this course (https://www.udemy.com/course/tdd-learn-test-driven-development-with-react-native/learn/lecture/25886826#questions) and the instructor is using this library but with an older version, 

I'm getting the catch error 

```
 console.warn
      undefined Cannot read properties of undefined (reading 'getCurrentPosition')

      12 |       .catch(error => {
      13 |         const {code, message} = error;
    > 14 |         console.warn(code, message);
         |                 ^
      15 |       });
      16 |   }
      17 | }

      at warn (src/services/LocationService/LocationService.ts:14:17)
```

this is my service: 

```
import GetLocation from 'react-native-get-location';

class LocationService {
  static async getCurrentPosition() {
    return GetLocation.getCurrentPosition({
      enableHighAccuracy: true,
      timeout: 60000,
    })
      .then(location => {
        console.log(location);
      })
      .catch(error => {
        const {code, message} = error;
        console.warn(code, message);
      });
  }
}

export default LocationService;
```
I've just used the code example to try to get the user location, i am wondering if this lib doesn't work with the IOS simulator or just with a device. 

link of the github repo: 
[https://github.com/rodrigodiasf1984/tdd-react-native](url)

Can you help? Thanks

**Comment by douglasjunior** [comment]
This error means that the library was not auto-linked.

Have you run the `pod install` after the `npm/yarn install`?

Please follow the install steps from [README](https://github.com/douglasjunior/react-native-get-location?tab=readme-ov-file#install) and after completing, rebuild and reinstall your app on the iOS simulator.

**Comment by rodrigodiasf1984** [comment]
Hello Douglas, can you reopen the issue please, i've follow the instructions and the package works on the simulator, i'm getting the error when i'm running my tests with jest, can you help me? 

![image](https://github.com/user-attachments/assets/613cec80-736e-4952-818a-41f71aecfc41)

**Comment by douglasjunior** [comment]
About the test, it's because you need to mock the package with jest.

Probably the course will teach you how to do the mock.
