### ISSUE TITLE
fetch Address from Lat-long

### ISSUE THREAD

**Issue by charmiswebiots** [douglasjunior/react-native-get-location#7]
Can I fetch address from lat-long using this package ??

**Comment by douglasjunior** [comment]
Not currently.

**Comment by NehaSixBerries** [comment]
> Can I fetch address from lat-long using this package ??

You can use geocoder npm.
https://www.npmjs.com/package/react-native-geocoder

**Comment by nasir03082409229** [comment]
Google's places API is not freely available I have another solution for geocoding location
Solution in Mapbox 
1. create free account here (https://studio.mapbox.com/)  & get `ACCESS TOKEN`
2. use this code snippet
`        fetch(`https://api.mapbox.com/geocoding/v5/mapbox.places/${LONGITUDE},${LATITUDE}.json?types=place&access_token=${MAPBOXGL_ACCCESS_TOKEN}`).then((res) => res.json()).then((res) => {
console.log(res) // * HERE IS YOUR GEOCODED JSON DATA
})`
For more info check the mapbox geocoding docs https://docs.mapbox.com/api/search/

**Comment by douglasjunior** [comment]
Android has a native Geocoding and Reverse Geocoding API https://developer.android.com/reference/android/location/Geocoder, but is not implemented yet in this library.
