### ISSUE TITLE
getCurrentPosition always times out

### ISSUE THREAD

**Issue by RadomirKus** [douglasjunior/react-native-get-location#9]
Hi, 

I am new to react-native-get-location but I am a big fan of it as it handles permissions for me.

However I keep bumping into TIMEOUT Location timed out unable to figure out why.

I am using RN 0.62 with autolinking and react-native-get-location 1.4.2.

So far I tried only Android.
The problem is, the very same code works on some phones but it times out on others. E.g. it fails on my Android 10.

What other information do you or how should I help yo debug this problem?

Thank you

- How did you link to the library (autolinking, manual, rn link, cocoapods)?
- What version of React Native?
- What version of the library?
- iOS/Android version?
- Did the problem happen after updating React Native?
- Are you using the library for the first time?
- It's a bug? Provide a link to a minimal reproduction case.

**Comment by douglasjunior** [comment]
The time required to obtain the location depends on several things, such as:
- Device model/brand
- GPS signal quality in your region
- Weather (number of clouds in the sky)
- Open or closed environment
- Etc

So, you need to configure the `timeout` as your need.

**Comment by RadomirKus** [comment]
It is not about the timeout though, other apps such as google maps get the location instantaneously, there is no way it would take google maps 1 second any my app over 1 minute when used on the same phone

**Comment by douglasjunior** [comment]
Other apps probably use Google Play Services to get the location in a smarter way, `react-natige-get-location` uses the location raw API.

Google Play Services uses several techniques to optimize location, including "sharing between apps", you can read a little more here: https://developers.google.com/android/guides/overview

**Comment by RadomirKus** [comment]
Allright, that is unfortunate. If I can not rely on getting location under two minutes there is no way I can incorporate this package to my app.

However I still believe there is something else going on. The timeout is just a mere fallback telling me it can not get the location for some reason even though it is supposed to. I refuse to believe it would take my phone over 2 minutes to get the location in nearly perfect conditions.

Thank you for you help

**Comment by douglasjunior** [comment]
Sorry, but this lib is used in several projects and we haven't found this situation yet, so I can't help you with that.

The native code thats get the location on Android is under this file https://github.com/douglasjunior/react-native-get-location/blob/master/android/src/main/java/com/github/douglasjunior/reactNativeGetLocation/util/GetLocation.java

It's a standart Android java code, feel free to debug and suggest changes.

**Comment by RadomirKus** [comment]
I've found the culprit. (Not in your code, but in mine.)

The problem disappeared when I changed enableHighAccuracy from false to true. At least on my phone. I had supposed it would work with coarse location as well but there is clearly something I do not understand. (I have WiFi turned on and working SIM card present in the phone.)

Anyway, it is working now with enableHighAccuracy: true. Thank you.

If it is of any help for your future development, meanwhile I found out there might be some issue within the raw location API, see:
https://github.com/Agontuk/react-native-geolocation-service

Quoting:
This library is created in an attempt to fix the location timeout issue on android with the react-native's current implementation of Geolocation API. This library tries to solve the issue by using Google Play Service's new FusedLocationProviderClient API, which Google strongly recommends over android's default framework location API.

To me it looks like the might be some flaw inside of the location API framework itself that causes timeouts on some devices. That is why they switched to Google Play Services API you mentioned earlier.

If it not of any help, sorry for bothering you and thank you for your time.

Cheers

**Comment by douglasjunior** [comment]
Good news! Thanks for the feedback!

`react-native-geolocation-service` talks about the deprecated [React Native Golocation API](https://reactnative.dev/docs/geolocation), which is really bad.

`react-native-get-location` uses the Android geolocation API as an alternative to the React Native Golocation API.

The Android geolocation API is the base of the GPS connection of the Android system, and the Google Play Location Services uses the Android geolocation API too.

The magic is that Google Play Location Services does a series of calculations on top of the fused and fine locations, and caches that information.
